name: Push

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate README.md
        run: ./generate.sh